"""
Pytest-Appium Script Exporter.
Transforms recorded interaction sequence into a standalone, executable Pytest suite
using Appium Python client and WebDriverWait.
Zero Qt dependencies.
"""
from __future__ import annotations

import logging
import re
from typing import Any, List, Mapping

from xgen.recorder.models import (
    ActionType, ExportResult, LocatorState, Recording, Step
)
from xgen.recorder.ports.exporter import Exporter

logger = logging.getLogger("xgen.recorder.exporters.pytest_appium")


class PytestAppiumExporter(Exporter):
    """
    Exports a recording as an executable Pytest test script using Appium.
    """
    id = "pytest_appium"
    display_name = "Pytest Appium Script"
    file_extension = "py"

    def option_schema(self) -> Mapping[str, Any]:
        return {
            "session_scope": {
                "enum": ["root", "app_launch", "top_level_window"],
                "default": "root",
            },
            "appium_url": {"type": "string", "default": "http://127.0.0.1:4723"},
            "explicit_wait_seconds": {"type": "number", "default": 10.0},
            "include_unverified": {"type": "boolean", "default": True},
            "parameterize_secrets": {"type": "boolean", "default": True},
        }

    def export(self, recording: Recording, options: Mapping[str, Any]) -> ExportResult:
        session_scope = options.get("session_scope", "root")
        appium_url = options.get("appium_url", "http://127.0.0.1:4723")
        explicit_wait = float(options.get("explicit_wait_seconds", 10.0))
        include_unverified = bool(options.get("include_unverified", True))
        parameterize_secrets = bool(options.get("parameterize_secrets", True))

        raw_name = recording.meta.name or recording.meta.id
        sanitized_name = re.sub(r"[^\w\d_]", "_", raw_name).strip("_").lower()
        if not sanitized_name:
            sanitized_name = "recording"

        # Determine target executable if available
        exe_path = ""
        for s in recording.steps:
            if s.process and s.process.exe_path:
                exe_path = s.process.exe_path.replace("\\", "\\\\")
                break

        warnings: List[str] = []
        lines: List[str] = []

        # Script Header and Imports
        lines.append('"""')
        lines.append(f'Auto-generated by xGen Recorder')
        lines.append(f'Session: {recording.meta.name} ({recording.meta.id})')
        lines.append(f'Generated at: {recording.meta.started_at}')
        lines.append('"""')
        lines.append("import os")
        lines.append("import time")
        lines.append("import pytest")
        lines.append("from appium import webdriver")
        lines.append("from appium.options.windows import WindowsOptions")
        lines.append("from appium.webdriver.common.appiumby import AppiumBy")
        lines.append("from selenium.webdriver.common.action_chains import ActionChains")
        lines.append("from selenium.webdriver.common.keys import Keys")
        lines.append("from selenium.webdriver.support.ui import WebDriverWait")
        lines.append("from selenium.webdriver.support import expected_conditions as EC")
        lines.append("")
        lines.append(f'EXPLICIT_WAIT = {explicit_wait}')
        lines.append("")
        lines.append("")
        lines.append("@pytest.fixture(scope=\"module\")")
        lines.append("def driver():")
        lines.append("    options = WindowsOptions()")

        if session_scope == "app_launch" and exe_path:
            lines.append(f'    options.set_capability("app", "{exe_path}")')
        else:
            lines.append('    options.set_capability("app", "Root")')

        lines.append(f'    _driver = webdriver.Remote("{appium_url}", options=options)')
        lines.append("    try:")
        lines.append("        yield _driver")
        lines.append("    finally:")
        lines.append("        _driver.quit()")
        lines.append("")
        lines.append("")
        lines.append("def _find(driver, xpath, timeout=EXPLICIT_WAIT):")
        lines.append("    return WebDriverWait(driver, timeout).until(")
        lines.append("        EC.presence_of_element_located((AppiumBy.XPATH, xpath))")
        lines.append("    )")
        lines.append("")
        lines.append("")
        lines.append(f"def test_{sanitized_name}(driver):")
        lines.append("    actions = ActionChains(driver)")
        lines.append("")

        if not recording.steps:
            lines.append("    # No steps recorded in this session")
            lines.append("    pass")

        secret_counter = 1
        sorted_steps = sorted(recording.steps, key=lambda s: s.seq)

        for step in sorted_steps:
            step_header = f"    # Step {step.seq}: {step.action.value.upper()}"
            if step.window and step.window.title:
                step_header += f" | Window: \"{step.window.title}\""
            lines.append(step_header)

            if step.notes:
                lines.append(f"    # Note: {step.notes}")

            # Locator determination
            xpath = ""
            loc_state = LocatorState.PENDING
            if step.locators:
                idx = step.selected_locator if (step.selected_locator is not None and 0 <= step.selected_locator < len(step.locators)) else 0
                loc = step.locators[idx]
                xpath = loc.xpath
                loc_state = loc.state

            is_unique = loc_state in (LocatorState.UNIQUE_IN_EVIDENCE, LocatorState.APPIUM_VERIFIED)

            if not is_unique and not include_unverified:
                warnings.append(f"Step {step.seq}: Suppressed unverified locator for {step.action.value}")
                lines.append(f"    # WARNING: Locator unverified ({loc_state.value}). Skipped action:")
                lines.append(f"    # _find(driver, {xpath!r}).{step.action.value}()")
                lines.append("")
                continue

            if not xpath and step.action not in (ActionType.WAIT, ActionType.SWITCH_WINDOW):
                pt = step.params.get("point", {})
                x = pt.get("x", step.params.get("x", 0))
                y = pt.get("y", step.params.get("y", 0))
                warnings.append(f"Step {step.seq}: Unresolved locator for {step.action.value} at ({x}, {y})")
                lines.append(f"    # NOTE: Unresolved element at coordinates ({x}, {y})")
                lines.append(f"    # actions.move_by_offset({x}, {y}).click().perform()")
                lines.append("")
                continue

            escaped_xpath = xpath.replace('"', '\\"')

            if step.action == ActionType.CLICK:
                lines.append(f'    _find(driver, "{escaped_xpath}").click()')
            elif step.action == ActionType.DOUBLE_CLICK:
                lines.append(f'    actions.double_click(_find(driver, "{escaped_xpath}")).perform()')
            elif step.action == ActionType.RIGHT_CLICK:
                lines.append(f'    actions.context_click(_find(driver, "{escaped_xpath}")).perform()')
            elif step.action == ActionType.TYPE:
                is_secret = bool(step.params.get("secret", False))
                text = str(step.params.get("text", ""))
                if is_secret and parameterize_secrets:
                    secret_env = f"SECRET_{secret_counter}"
                    secret_counter += 1
                    lines.append(f'    _val = os.environ.get("{secret_env}", {text!r})')
                    lines.append(f'    _find(driver, "{escaped_xpath}").send_keys(_val)')
                else:
                    lines.append(f'    _find(driver, "{escaped_xpath}").send_keys({text!r})')
            elif step.action == ActionType.KEY_PRESS:
                keys_list = step.params.get("keys", [])
                mapped_keys = [self._map_key(k.upper()) for k in keys_list]
                if len(mapped_keys) > 1:
                    args_str = ", ".join(mapped_keys)
                    lines.append(f'    actions.send_keys({args_str}).perform()')
                elif mapped_keys:
                    lines.append(f'    actions.send_keys({mapped_keys[0]}).perform()')
            elif step.action == ActionType.SCROLL:
                dx = step.params.get("dx", 0)
                dy = step.params.get("dy", 0)
                lines.append(f'    actions.scroll_by_amount({dx}, {dy}).perform()')
            elif step.action == ActionType.WAIT:
                dur = step.params.get("value", 1.0)
                lines.append(f'    time.sleep({dur})')
            elif step.action == ActionType.SWITCH_WINDOW:
                target_title = step.params.get("to_window", {}).get("title", "") if isinstance(step.params.get("to_window"), dict) else ""
                lines.append(f'    # Target window switched to: "{target_title}"')
            else:
                lines.append(f'    # Action {step.action.value} on "{escaped_xpath}"')

            lines.append("")

        script_text = "\n".join(lines)
        filename = f"test_{sanitized_name}.py"

        return ExportResult(
            text=script_text,
            filename=filename,
            warnings=warnings,
            stats={"step_count": len(recording.steps), "warnings_count": len(warnings)}
        )

    @staticmethod
    def _map_key(k_upper: str) -> str:
        common_keys = {
            "CTRL": "Keys.CONTROL",
            "CONTROL": "Keys.CONTROL",
            "ALT": "Keys.ALT",
            "SHIFT": "Keys.SHIFT",
            "WIN": "Keys.COMMAND",
            "CMD": "Keys.COMMAND",
            "COMMAND": "Keys.COMMAND",
            "ENTER": "Keys.ENTER",
            "RETURN": "Keys.RETURN",
            "TAB": "Keys.TAB",
            "ESCAPE": "Keys.ESCAPE",
            "ESC": "Keys.ESCAPE",
            "BACKSPACE": "Keys.BACKSPACE",
            "DELETE": "Keys.DELETE",
            "SPACE": "Keys.SPACE",
            "UP": "Keys.UP",
            "DOWN": "Keys.DOWN",
            "LEFT": "Keys.LEFT",
            "RIGHT": "Keys.RIGHT",
            "HOME": "Keys.HOME",
            "END": "Keys.END",
            "PAGE_UP": "Keys.PAGE_UP",
            "PAGE_DOWN": "Keys.PAGE_DOWN",
        }
        if len(k_upper) == 1 and k_upper.isalnum():
            return repr(k_upper.lower())
        return common_keys.get(k_upper, f"getattr(Keys, {k_upper!r}, {k_upper!r})")
